CREATE TABLE Autor(
	CPF VARCHAR(14) PRIMARY KEY,
	nome VARCHAR(50) NOT NULL UNIQUE,
	email VARCHAR(40) NOT NULL
);
CREATE TABLE Livro(
	ISBN VARCHAR(18) PRIMARY KEY,
	descricao VARCHAR(100) NOT NULL,
	edicao VARCHAR(50) NOT NULL
);
CREATE TABLE AutorLibro(
	ISBN VARCHAR(50) NOT NULL,
	nomeAutor VARCHAR(50) NOT NULL,
	FOREIGN KEY (nomeAutor) REFERENCES Autor (nome)
)
	
	
